### ISSUE TITLE
Issue 6 for Milestone 3: Training the Model (Lab 5-8)

### ISSUE THREAD

**Issue by Bernard-Otieno** [Bernard-Otieno/Bi-Project-Credit-card-Fraud#6]
- [ ] Data splitting
- [ ] Bootstrapping
- [ ] Cross validation (basic, repeated, or LOOCV)
- [ ] Model training for either classification, regression, association, or clustering (as applicable)
- [ ] Model performance comparison using resamples (for classification and regression)
